services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - football-network

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: football
    ports:
      - "5433:5432"
    networks:
      - football-network

  cron-job:
    build: 
      context: .
      dockerfile: cron-job/Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - football-network

networks:
  football-network:
    driver: bridge